<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.2.2 setup script
 * Date: Tue, 27 May 2014 17:28:41 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: rdbms.strato.de [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'rdbms.strato.de';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'U1695068';
$cfg['Servers'][$i]['password'] = 'DBWE05org';

/* End of servers configuration */

$cfg['blowfish_secret'] = '5384a0c839ce49.19307170';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>